name: 'tech_market_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tech_market_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  tech_market_analytics:
    raw_company_info:
      +schema: raw
      +quote_columns: false
      +column_types:
        shares_outstanding: bigint
        earnings_per_share: float
    raw_stock_prices:
      +schema: raw
      +quote_columns: false
      +column_types:
        volume: bigint
        open: float
        high: float
        low: float
        close: float 