version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"

  dbt:
    build:
      context: .
      dockerfile: docker/dbt.Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dbt:/dbt

volumes:
  postgres_data: 