version: 2

sources:
  - name: raw
    schema: public_raw
    tables:
      - name: raw_stock_prices
        description: Raw daily stock prices from Alpha Vantage
        columns:
          - name: symbol
            description: Stock symbol
            tests:
              - not_null
          - name: date
            description: Trading date
            tests:
              - not_null
          - name: open
            description: Opening price
          - name: high
            description: Highest price
          - name: low
            description: Lowest price
          - name: close
            description: Closing price
          - name: volume
            description: Trading volume

      - name: raw_company_info
        description: Raw company information from Alpha Vantage
        columns:
          - name: symbol
            description: Stock symbol
            tests:
              - not_null
          - name: company_name
            description: Company name
            tests:
              - not_null
          - name: sector
            description: Business sector
          - name: industry
            description: Industry
          - name: country
            description: Country
          - name: shares_outstanding
            description: Shares outstanding
          - name: currency
            description: Currency
          - name: earnings_per_share
            description: EPS

models:
  - name: stg_daily_prices
    description: Cleaned and parsed daily stock prices
    columns:
      - name: symbol
        description: Stock symbol
        tests:
          - not_null
      - name: trading_date
        description: Date of the trading day
        tests:
          - not_null
      - name: open_price
        description: Opening price
        tests:
          - not_null
      - name: high_price
        description: Highest price
        tests:
          - not_null
      - name: low_price
        description: Lowest price
        tests:
          - not_null
      - name: close_price
        description: Closing price
        tests:
          - not_null
      - name: volume
        description: Trading volume
        tests:
          - not_null
      - name: extracted_at
        description: Timestamp when data was extracted
        tests:
          - not_null
      - name: transformed_at
        description: Timestamp when data was transformed
        tests:
          - not_null

  - name: stg_company_info
    description: Cleaned and parsed company information
    columns:
      - name: symbol
        description: Stock symbol
        tests:
          - not_null
          - unique
      - name: company_name
        description: Company name
        tests:
          - not_null
      - name: sector
        description: Business sector
      - name: industry
        description: Business industry
      - name: country
        description: Country
      - name: shares_outstanding
        description: Shares outstanding
      - name: currency
        description: Currency
      - name: earnings_per_share
        description: EPS
      - name: created_at
        description: Record creation timestamp
        tests:
          - not_null
      - name: updated_at
        description: Record update timestamp
        tests:
          - not_null 